[features]
seeds = false
skip-lint = false
[programs.localnet]
pineapple_or_not = "4cnMefx5UmwwW6yCJYMoLAGzQy8XVq7AQRKqFsP7aajh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/arihantbansal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
